// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHrEq_bBDe902iRX_qXqMfQd-UgpqnGPo',
    appId: '1:407357129583:web:a5347a29e7483a04729e9a',
    messagingSenderId: '407357129583',
    projectId: 'stocklistmanager-80a4f',
    authDomain: 'stocklistmanager-80a4f.firebaseapp.com',
    storageBucket: 'stocklistmanager-80a4f.firebasestorage.app',
    databaseURL: 'https://stocklistmanager-80a4f-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHrEq_bBDe902iRX_qXqMfQd-UgpqnGPo',
    appId: '1:407357129583:android:d2336557e62bfd26729e9a',
    messagingSenderId: '407357129583',
    projectId: 'stocklistmanager-80a4f',
    storageBucket: 'stocklistmanager-80a4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHrEq_bBDe902iRX_qXqMfQd-UgpqnGPo',
    appId: '1:407357129583:ios:d2336557e62bfd26729e9a',
    messagingSenderId: '407357129583',
    projectId: 'stocklistmanager-80a4f',
    storageBucket: 'stocklistmanager-80a4f.firebasestorage.app',
    iosBundleId: 'com.example.stocklistmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHrEq_bBDe902iRX_qXqMfQd-UgpqnGPo',
    appId: '1:407357129583:ios:d2336557e62bfd26729e9a',
    messagingSenderId: '407357129583',
    projectId: 'stocklistmanager-80a4f',
    storageBucket: 'stocklistmanager-80a4f.firebasestorage.app',
    iosBundleId: 'com.example.stocklistmanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTbzpNQ3oXAElb7Tbmk1stNB8XItz3SfI',
    appId: '1:407357129583:web:a5347a29e7483a04729e9a',
    messagingSenderId: '407357129583',
    projectId: 'stocklistmanager-80a4f',
    authDomain: 'stocklistmanager-80a4f.firebaseapp.com',
    storageBucket: 'stocklistmanager-80a4f.firebasestorage.app',
  );
}
